# Generated by Django 3.1.3 on 2020-11-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrossPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovrpsNm', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
                ('rdnmadr', models.CharField(max_length=100)),
                ('handicapCvntlYn', models.CharField(max_length=1)),
                ('handicapCvntlType', models.CharField(max_length=10)),
                ('handicapCvntlCo', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
