# Generated by Django 3.1 on 2020-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
